routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('home');
Route::get('data-tables', 'IndexController@dataTable')->name('table');

Route::get('register', 'AuthController@register')->name('register');
Route::get('welcome', 'AuthController@welcome')->name('welcome');

Route::resource('cast', CastController::class);

app/Cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
  protected $table = "cast";
  protected $fillable = ["nama", "umur", "bio"];
  public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AuthController extends Controller
{
  public function register()
  {
    return view('register');
  }

  public function welcome(Request $request)
  {
    $data = $request->query();
    return view('welcomed', compact('data'));
  }
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cast;

class CastController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $casts = Cast::all();
      return view('cast.index', compact('casts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('cast.create', ['title' => 'Tambah Pemain']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validated = $this->validate($request,[
    		'nama' => 'required|string',
    		'umur' => 'required|integer|min:0',
        'bio' => 'required|string'
    	]);
      
      Cast::create($validated);

      return redirect(route('cast.index'))->with('success', 'data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $cast = Cast::find($id);

      return view('cast.show', compact('cast'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $cast = Cast::find($id);
      $title = 'Edit Pemain';
      return view('cast.create', compact('cast', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $validated = $this->validate($request,[
    		'nama' => 'required|string',
    		'umur' => 'required|integer|min:0',
        'bio' => 'required|string'
    	]);

      $cast = Cast::find($id);
      $cast->nama = $validated['nama'];
      $cast->umur = $validated['umur'];
      $cast->bio = $validated['bio'];

      $cast->update();

      return redirect(route('cast.show', $id))->with('success', 'Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $cast = Cast::find($id);
      $cast->delete();

      return redirect(route('cast.index'))->with('success', 'Data berhasil dihapus');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IndexController extends Controller
{
  public function home()
  {
    return view('index');
  }

  public function dataTable()
  {
    return view('table');
  }
}

resources/views/cast/create.blade.php
@extends('layout.main')

@section('title', $title)

@section('content')
  <div class="row justify-content-center">
    <div class="col-md-6 col-12">

    @if (isset($cast))
      <form action="{{route('cast.update', $cast->id)}}" method="post">
      @method('PUT')
    @else
      <form action="{{route('cast.store')}}" method="post">
    @endif

        @if ($errors->any())
          <div class="alert alert-danger" role="alert">
            <ul>
              @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
        @endif

        @csrf
        <div class="form-group">
          <label for="name">Nama</label>
          <input type="text" class="form-control @error('nama') is-invalid @enderror" id="name" name="nama" value="{{$cast->nama??old('nama')}}" required>
          @error('nama')
            <div id="" class="invalid-feedback">
              {{$message}}
            </div>
          @enderror
        </div>

        <div class="form-group">
          <label for="age">umur</label>
          <input type="number" class="form-control @error('title') is-invalid @enderror" id="age" name="umur" min="0" step="1" value="{{$cast->umur??old('nama')}}" required>
          @error('umur')
            <div id="" class="invalid-feedback">
              {{$message}}
            </div>
          @enderror
        </div>

        <div class="form-group">
          <label for="bio">Example textarea</label>
          <textarea class="form-control @error('title') is-invalid @enderror" id="bio" rows="3" name="bio" required>{{$cast->bio??old('nama')}}</textarea>
          @error('bio')
            <div id="" class="invalid-feedback">
              {{$message}}
            </div>
          @enderror
        </div>

        @if (isset($cast))
          <a role="button" href="{{route('cast.show', $cast->id)}}" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Batal
          </a>
          <button type="submit" class="btn btn-warning">
            <i class="fas fa-edit"></i> Update
          </button>
        @else
          <button type="submit" class="btn btn-primary">
            <i class="fas fa-save"></i> Simpan
          </button>
        @endif   
      </form>
    </div>
  </div>
@endsection

resources/views/cast/index.blade.php
@extends('layout.main')

@section('title', 'Daftar Pemain')

@push('styles')
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
@endpush

@section('card-tools')
  <a class="btn btn-success btn-sm" href="{{route('cast.create')}}" role="button">
    <i class="fas fa-plus"></i> Tambah Pemain
  </a>
@endsection

@push('scripts')
  <script src="{{asset('plugins/datatables/jquery.dataTables.js')}}"></script>
  <script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
  <script>
    $(function () {
      $("#example1").DataTable();
    });
  </script>
@endpush

@section('content')
  @if (!count($casts))
    <div class="text-center d-block">
      Belum ada data. <a href="{{route('cast.create')}}">Tambahkan data sekarang!</a>
    </div>
  @else
    <div class="row">
      <div class="col-12">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>#</th>
            <th>Nama</th>
            <th>Umur</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody>
            @foreach ($casts as $cast)
              <tr>
                <td>{{$loop->index+1}}</td>
                <td>{{$cast->nama}}</td>
                <td>{{$cast->umur}}</td>
                <td class="text-center">
                  <a class="btn btn-primary" href="{{route('cast.show', $cast->id)}}" role="button">
                    <i class="fas fa-eye"></i> detail
                  </a>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  @endif

@endsection

resources/views/cast/show.blade.php
@extends('layout.main')

@section('title', 'Detail Pemain')

@section('content')
  <div class="row">
    <div class="col-12">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="col-auto font-weight-bold">Nama</td>
            <td class="col-auto">:</td>
            <td class="col">{{$cast->nama}}</td>
          </tr>
          <tr>
            <td class="font-weight-bold">Umur</td>
            <td>:</td>
            <td>{{$cast->umur}}</td>
          </tr>
          <tr>
            <td class="font-weight-bold">Bio</td>
            <td>:</td>
            <td>{{$cast->bio}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-right">
      <a href="{{route('cast.edit', $cast->id)}}" role="button" class="btn btn-warning">
        <i class="fas fa-edit"></i> Edit
      </a>
      <button type="button" class="btn btn-danger ml-2" data-toggle="modal" data-target="#exampleModal">
        <i class="fas fa-trash"></i> Hapus
      </button>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header border-0">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body text-center">
          Hapus data pemain <strong>{{$cast->nama}}</strong>?
        </div>
        <div class="modal-footer border-0">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <i class="fas fa-ban"></i> Batal
          </button>
          <form action="{{route('cast.destroy', $cast->id)}}" method="POST">
            @method('DELETE')
            @csrf
            <button type="submit" class="btn btn-danger" role="button">
              <i class="fas fa-trash"></i> Hapus
            </a>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/index.blade.php
@extends('layout.main')

@section('title', 'Halaman Home')

@section('content')
  <h1>Media Online</h1>
  <h2>Sosial Media Developer</h2>
  <p>Belajar dan berbagi agar hidup menjadi lebih baik</p>
  <h3>Benefit join di Media Online</h3>
  <ul>
    <li>Mendapatkan motovasi dari sesama para Developer</li>
    <li>Sharing knowledge</li>
    <li>Dibuat oleh calon developer terbaik</li>
  </ul>
  <h3>Cara bergabung ke Media Online</h3>
  <ol>
    <li>Mengunjungi Website ini</li>
    <li>Mendaftar di <a href="{{route('register')}}">Form Sign Up</a></li>
    <li>Selesai</li>
  </ol>
@endsection

resources/views/layout/main.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    @yield('title')
  </title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('css/adminlte.min.css')}}">

  @stack('styles')
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    {{-- <ul class="ml-auto navbar-nav">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="mr-3 img-size-50 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="mr-1 far fa-clock"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="mr-3 img-size-50 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="mr-1 far fa-clock"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="mr-3 img-size-50 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="mr-1 far fa-clock"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="mr-2 fas fa-envelope"></i> 4 new messages
            <span class="float-right text-sm text-muted">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="mr-2 fas fa-users"></i> 8 friend requests
            <span class="float-right text-sm text-muted">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="mr-2 fas fa-file"></i> 3 new reports
            <span class="float-right text-sm text-muted">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul> --}}
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('layout.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="mb-2 row">
          <div class="col-sm-6">
            <h1 class="m-0">
              @yield('title')
            </h1>
          </div><!-- /.col -->
          {{-- <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Starter Page</li>
            </ol>
          </div><!-- /.col --> --}}
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">

        @if (session('success'))
          <div class="row">
            <div class="col-12 alert alert-success" role="alert">
              {{ session('success') }}
            </div>
          </div>
        @endif

        <div class="row">
          <div class="col-lg-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">
                  @yield('title')
                </h3>

                <div class="card-tools">
                  {{-- <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                  </button> --}}
                  @yield('card-tools')
                </div>
              </div>
              <div class="card-body">
                @yield('content')
              </div>
            </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('js/adminlte.min.js')}}"></script>

@stack('scripts')
</body>
</html>

resources/views/layout/sidebar.blade.php
@php
    $sidebarMenus = [
      [
        'title' => 'Dashboard',
        'link' => route('home'),
        'icon' => 'fas fa-tachometer-alt',
        'child' => []
      ],
      [
        'title' => 'Table',
        'link' => '#',
        'icon' => 'fas fa-th',
        'child' => [
          [
            'title' => 'Data Table',
            'link' => route('table'),
            'icon' => 'far fa-circle',
          ],
        ]
      ],
      [
        'title' => 'Pemain',
        'link' => '#',
        'icon' => 'far fa-meh',
        'child' => [
          [
            'title' => 'Data Pemain',
            'link' => route('cast.index'),
            'icon' => 'far fa-circle',
          ],
          [
            'title' => 'Tambah Pemain',
            'link' => route('cast.create'),
            'icon' => 'fas fa-plus',
          ],
        ]
      ],
    ]
@endphp

<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img src="{{asset('img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="pb-3 mt-3 mb-3 user-panel d-flex">
      <div class="image">
        <img src="{{asset('img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">Alexander Pierce</a>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        
        @foreach ($sidebarMenus as $menu)     
          <li class="nav-item">
            <a href="{{$menu['link']}}" class="nav-link">
              <i class="nav-icon {{$menu['icon']}}"></i>
              <p>
                {{$menu['title']}}
                @if (count($menu['child']))
                  <i class="right fas fa-angle-left"></i>    
                @endif
              </p>
            </a>
            @if (count($menu['child']))
              <ul class="nav nav-treeview">
                @foreach ($menu['child'] as $child)
                    <li class="nav-item">
                      <a href="{{$child['link']}}" class="nav-link">
                        <i class="nav-icon {{$child['icon']}}"></i>
                        <p>{{$child['title']}}</p>
                      </a>
                    </li>                  
                @endforeach
              </ul>
            @endif
          </li>
        @endforeach
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

resources/views/register.blade.php
@extends('layout.main')

@section('title', 'Halaman Home')

@section('content')
<form action="{{route('welcome')}}" method="GET">
    <h1>Buat Account Baru</h1>

    <h3>Sign Up Form</h3>

    <label>First name :</label><br/>
    <input type="text" name="first_name" /><br/><br/>

    <label>Last name :</label><br/>
    <input type="text" name="last_name" /><br/><br/>

    <label>Gender</label><br/>
    <input type="radio" value="male" name="gender"/> Male<br/>
    <input type="radio" value="female" name="gender"/> Female<br/><br/>

    <label>Nationality</label><br/>
    <select name="nationality">
        <option value="indonesia">Indonesia</option>
        <option value="foreign">Foreign</option>
    </select><br/><br/>

    <label>Language Spoken</label><br/>
    <input type="checkbox" name="language" value="bahasa"> Bahasa Indonesia<br/>
    <input type="checkbox" name="language" value="english">
    English<br/>
    <input type="checkbox" name="language" value="other"> Other<br/><br/>

    <label>Bio</label><br/>
    <textarea name="bio"></textarea><br/><br/>

    <input type="submit" value="Sign Up"/>
</form>
@endsection

resources/views/welcomed.blade.php
@extends('layout.main')

@section('title', 'Halaman Home')

@section('content')
  <h1>SELAMAT DATANG! {{$data['first_name']}} {{$data['last_name']}}</h1>
  <h3>Terima kasih telah bergabung di Website Kami. Media Belajar kita bersama!</h3>
@endsection